### ISSUE TITLE
Complete Rename

### ISSUE THREAD

**Issue by SimpleBinary** [citrus-lang/Citrus#17]
This issue will remain open until we have updated these things to include the new names and logos:
- Docs
- VSCode extension (and publish it)
- Teams
- Any other information

**The Citrus Team**

**Comment by Dandigit** [comment]
@SimpleBinary We've also got to rename `citrusError` to `CitrusError` - it's a type, and should have a capital letter.

**Comment by SimpleBinary** [comment]
Ok

**Comment by SimpleBinary** [comment]
@Dandigit It'll be easy

**Comment by BonfireScratch** [comment]
@SimpleBinary can you help to rewrite the N# lexer, please?

**Comment by SimpleBinary** [comment]
@BonfireScratch Please don't post irrelevant stuff on Citrus issues, could you `@simplebinary` me from one of your N# issues.

**Comment by BonfireScratch** [comment]
@SimpleBinary it seems like you haven't updated the extension and the marketplace page

**Comment by otsfan203** [comment]
Oh, I was confused. I was looking for Solar, and couldn't find it.

**Comment by otsfan203** [comment]
Also...
1. I made a pull request for Citrusization for the VSCode extension.
2. I made a pull request for Citrusization for the website.

I know I'm not part of the Citrus Team but I just wanted to help out :)

**Comment by SimpleBinary** [comment]
@otsfan203 @BonfireScratch @Dandigit Solar has been renamed to Citrus. Please report any times you see Solar instead of Citrus though.
