### ISSUE TITLE
Needs major refactor

### ISSUE THREAD

**Issue by Dandigit** [citrus-lang/citrus#18]
I wrote a lot of the code for Citrus in a "as long as it works" fashion, without much regard to readability or conciseness. This was fine at the time, as Citrus was still super unstable, but as we approach 0.4.0 I think that it's time to clean up the code a bit. I'm going to leave this open until the refactor is done.

**Comment by SimpleBinary** [comment]
@Dandigit So we should put try...catch loops around them. Correct?

**Comment by Dandigit** [comment]
@SimpleBinary ???
Not sure if you're joking or are actually serious...

**Comment by Dandigit** [comment]
Oops - didn't mean to close this

**Comment by SimpleBinary** [comment]
@Dandigit I misread it. sorry.
